modLoader="javafml" #mandatory

loaderVersion="[1,)" #mandatory

license="MIT"

[[mods]] #mandatory
modId="spruceui_test" #mandatory
version="0.0.0" #mandatory
displayName="SpruceUI test" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''Just a GUI library.'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
config="spruceui.test.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"
